# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25d84442b99ff037a687b25477c985925cfa542974426b36bc4cecc6bb0fd9295260227e764a42e1b68333ea06902580fb10ff7f90cdc5eb5bf4e301c8780d56

test:
  secret_key_base: 1cf4d30ae798fb4207b26ab55a638f552cf4cabfca3beb676eb7a0d45cc8202dba65e2a015a8428c1fc4c216109b8617fcd4cd20c9652b7eca4b403b7c36feae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
